name: lab

on:
  push:
  schedule:
    - cron: '0 16 */1 * *'

jobs:
  hub:
    runs-on: ubuntu-20.04
    steps:
    - name: timer
      run: |
          echo `date`

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: 'https://github.com/hoppscotch/hoppscotch.git'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to official hub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          sqjian/venv:hoppscotch