name: lab

on:
  push:
  schedule:
    - cron: '0 16 */1 * *'

jobs:
  hub:
    runs-on: ubuntu-20.04
    steps:
    - name: timer
      run: |
          echo `date`
    - name: Checkout code
      uses: actions/checkout@v2
    - name: dos2unix
      run: |
          sudo apt-get install -y dos2unix
          find docker -type f | xargs dos2unix
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: venv/docker/ubuntu
        file: venv/docker/ubuntu/lab.dockerfile
        push: true
        tags: |
          sqjian/artifact:lab
    # - name: Build and push Docker images to official hub
    #   uses: docker/build-push-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #     repository: sqjian/artifact
    #     tags: "lab"
    #     context: venv/docker/ubuntu
    #     file: venv/docker/ubuntu/lab.dockerfile
    # - name: Build and push Docker images to aliyun hub
    #   uses: docker/build-push-action@v1
    #   with:
    #     username: ${{ secrets.ALY_DOCKER_USERNAME }}
    #     password: ${{ secrets.ALY_DOCKER_PASSWORD }}
    #     registry: registry.cn-hangzhou.aliyuncs.com
    #     repository: sqjian/artifact
    #     tags: "lab"
    #     path: venv/docker/ubuntu
    #     dockerfile: venv/docker/ubuntu/lab.dockerfile