name: lab

on:
  create:
  schedule:
    - cron: '0 16 */1 * *'

jobs:
  hub:
    runs-on: ubuntu-20.04
    steps:
    - name: timer
      run: |
          echo `date`

    - name: Checkout code
      uses: actions/checkout@v2

    - name: dos2unix
      run: |
          sudo apt-get install -y dos2unix
          find -type f -name *.sh| xargs dos2unix

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to official hub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: venv/docker/ubuntu
        file: venv/docker/ubuntu/lab.dockerfile
        push: true
        tags: |
          sqjian/artifact:lab