name: ubuntu_20.04

on:
  create:
  schedule:
    - cron: '0 16 */1 * *'

jobs:
  hub:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: dos2unix
      run: |
          sudo apt-get install -y dos2unix
          find docker -type f | xargs dos2unix
    - name: Build and push Docker images to official hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: sqjian/artifact
        tags: "ubuntu20_04"
        path: venv/docker/ubuntu
        dockerfile: venv/docker/ubuntu/ubuntu20_04.dockerfile
    - name: Build and push Docker images to aliyun hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.ALY_DOCKER_USERNAME }}
        password: ${{ secrets.ALY_DOCKER_PASSWORD }}
        registry: registry.cn-hangzhou.aliyuncs.com
        repository: sqjian/artifact
        tags: "ubuntu20_04"
        path: venv/docker/ubuntu
        dockerfile: venv/docker/ubuntu/ubuntu20_04.dockerfile